<a href="https://colab.research.google.com/github/sashwat97/AIML/blob/main/NumPy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
a = np.array([1,2,3])
b = np.array([(1.5,2,3), (4,5,6)], dtype = float)
c = np.array([[(1.5,2,3), (4,5,6)], [(3,2,1), (4,5,6)]],dtype = float)

In [ ]:
a

array([1, 2, 3])

In [ ]:
b

array([[1.5, 2. , 3. ],
       [4. , 5. , 6. ]])

In [ ]:
d = np.array([4,5,6])

In [ ]:
e = a+d

In [ ]:
e


array([5, 7, 9])

In [ ]:
 f = b = np.array([(5,2,3), (13,5,6)], dtype = float)

In [ ]:
g = b + f


In [ ]:
g

array([[10.,  4.,  6.],
       [26., 10., 12.]])

In [ ]:
a.sort()

In [ ]:
a


array([1, 2, 3])

In [ ]:
g.sort()

In [ ]:
g

array([[ 4.,  6., 10.],
       [10., 12., 26.]])